version: "3.9"
services:
  app:
    container_name: "timezync-server"
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - .:/app
      - ./database:/app/database
    environment:
      - FLASK_ENV=development
      - SECRET_KEY=secret
      - FLASK_APP=timezync
    command: flask run --host=0.0.0.0 --port=5000 --reload
